name: Build Windows (custom)

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            mingw-w64-ucrt-x86_64-boost
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-cppwinrt
            mingw-w64-ucrt-x86_64-curl-winssl
            mingw-w64-ucrt-x86_64-MinHook
            mingw-w64-ucrt-x86_64-miniupnpc
            mingw-w64-ucrt-x86_64-nodejs
            mingw-w64-ucrt-x86_64-nsis
            mingw-w64-ucrt-x86_64-onevpl
            mingw-w64-ucrt-x86_64-openssl
            mingw-w64-ucrt-x86_64-opus
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-nlohmann_json
            mingw-w64-ucrt-x86_64-ninja

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja

      - name: Package NSIS installer
        run: |
          cd build
          cpack -G NSIS

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Apollo-Windows-Installer
          path: build/cpack_artifacts/*.exe
          if-no-files-found: error
